### ISSUE TITLE
isl-0.20 support

### ISSUE THREAD

**Issue by ftynse** [periscop/cloog#42]
isl released a new version, there were some random reports about failing tests in CLooG's mailing list, which may be related

@harenome @Syllo want to take a look?

**Comment by Syllo** [comment]
It seems like that they were some header missing in CLooG's isl interface.
I'm running the check and will push the patch shortly.

**Comment by Syllo** [comment]
I've pushed the fix to the branch isl-0.20 (6faa51a19668aa419e4de944382c5c1374490ac1).

It seems to work fine but I currently do not have the time to verify the tests that produce a different code output. They pass with the C checker because of the hybrid method but the Fortran checker does not have it, hence the final check fail.

**Comment by f0086** [comment]
Thank you for the patch for the failing tests (maintainer on the cloog package on ArchLinux). But one test still failed:

```

PASS: test/check_c.sh
FAIL: test/check_fortran.sh
PASS: test/check_strided.sh
PASS: test/check_openscop.sh
PASS: test/check_special.sh
============================================================================
Testsuite summary for cloog 0.19.0
============================================================================
# TOTAL: 5
# PASS:  4
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
```
